#app.yaml
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: mysql.sys
  CLOUD_SQL_PASSWORD:
  CLOUD_SQL_DATABASE_NAME: db_demo
  CLOUD_SQL_CONNECTION_NAME: myip
#TESTing testrt

#  handlers:
# - url: /
#   static_files: HACKATHON/flask-app
#   upload: HACKATHON/flask-app

# - url: /(.*)
#   static_files: HACKATHON/\1
#   upload: HACKATHON/(.*)